language: ruby

sudo: false

rvm:
  - 2.3.0
  - 2.2.3
  - 2.1.7
  - rbx-2
  - jruby-19mode

matrix:
  allow_failures:
    - rvm: rbx-2
env:
  - GRAPE_VERSION=0.12.0
  - GRAPE_VERSION=0.13.0
  - GRAPE_VERSION=0.14.0
  # - GRAPE_VERSION=HEAD
