language: ruby

sudo: false

matrix:
  include:
    - rvm: 2.3.1
      env: GRAPE_VERSION=0.12.0
    - rvm: 2.3.1
      env: GRAPE_VERSION=0.13.0
    - rvm: 2.3.1
      env: GRAPE_VERSION=0.14.0
    - rvm: 2.3.1
      env: GRAPE_VERSION=0.15.0
#    - rvm: 2.3.1
#      env: GRAPE_VERSION=0.16.0
#    - rvm: 2.3.1
#      env: GRAPE_VERSION=HEAD
    - rvm: 2.3.0
    - rvm: 2.2.5
    - rvm: 2.1
    - rvm: rbx-2
    - rvm: jruby-19mode
    - rvm: ruby-head
    - rvm: jruby-head
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-19mode
    - rvm: ruby-head
    - rvm: jruby-head
