language: ruby

os: linux

before_install:
  - gem install bundler

after_success:
  - bundle exec danger

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
env:
  - GRAPE_VERSION=1.3.3
  - GRAPE_VERSION=1.4.0 MODEL_PARSER=grape-swagger-entity
  - GRAPE_VERSION=1.4.0 MODEL_PARSER=grape-swagger-representable
  - GRAPE_VERSION=1.4.0
  - GRAPE_VERSION=HEAD

jobs:
  fast_finish: true

  include:
    - rvm: 2.4.10
      env:
    - rvm: ruby-head
      env:
    - rvm: jruby-head
      env:

  allow_failures:
    - rvm: 2.4.10
    - rvm: ruby-head
    - rvm: jruby-head
