language: ruby

sudo: false

rvm:
  - 2.3
  - 2.2
  - 2.1
  - jruby-19mode
  - rbx-2

env:
  - GRAPE_VERSION=0.8.0
  - GRAPE_VERSION=0.9.0
  - GRAPE_VERSION=0.10.0
  - GRAPE_VERSION=0.10.1
  - GRAPE_VERSION=0.11.0
  - GRAPE_VERSION=0.12.0
  - GRAPE_VERSION=0.13.0
  - GRAPE_VERSION=0.14.0
  # - GRAPE_VERSION=HEAD

matrix:
  allow_failures:
    - rvm: rbx-2
