language: ruby

sudo: false

before_install:
  - gem update --system
  - gem install bundler

after_success:
  - coveralls
  - bundle exec danger

rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.0-preview2
env:
  - MODEL_PARSER=grape-swagger-entity
  - MODEL_PARSER=grape-swagger-representable
  - GRAPE_VERSION=0.19.2
  - GRAPE_VERSION=1.0.3
  - GRAPE_VERSION=1.2.0
  - GRAPE_VERSION=HEAD

matrix:
  fast_finish: true

  include:
    - rvm: 2.3.8
      env:
    - rvm: ruby-head
      env:
    - rvm: jruby-head
      env:

  allow_failures:
    - rvm: 2.3.7
    - rvm: ruby-head
    - rvm: jruby-head
