language: ruby

sudo: false

before_install:
  - gem install bundler

after_success:
  - bundle exec danger

rvm:
  - 2.4.5
  - 2.5.4
  - 2.6.2
env:
  - MODEL_PARSER=grape-swagger-entity
  - MODEL_PARSER=grape-swagger-representable
  - GRAPE_VERSION=1.0.3
  - GRAPE_VERSION=1.2.2
  - GRAPE_VERSION=HEAD

matrix:
  fast_finish: true

  include:
    - rvm: 2.3.8
      env:
    - rvm: ruby-head
      env:
    - rvm: jruby-head
      env:

  allow_failures:
    - rvm: 2.3.8
    - rvm: ruby-head
    - rvm: jruby-head
